{"componentChunkName":"component---node-modules-atooni-gatsby-theme-ziodoc-src-components-simple-js","path":"/zio/1-0-0/datatypes/core/cause","result":{"data":{"mdx":{"id":"2dbbca08-0aa5-5af7-81dc-5ded48256226","slug":"datatypes/core/cause","body":"var _excluded = [\"components\"];\n\nfunction _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }\n\nfunction _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }\n\nfunction _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }\n\n/* @jsxRuntime classic */\n\n/* @jsx mdx */\nvar _frontmatter = {\n  \"id\": \"cause\",\n  \"title\": \"Cause\"\n};\nvar layoutProps = {\n  _frontmatter: _frontmatter\n};\nvar MDXLayout = \"wrapper\";\nreturn function MDXContent(_ref) {\n  var components = _ref.components,\n      props = _objectWithoutProperties(_ref, _excluded);\n\n  return mdx(MDXLayout, _extends({}, layoutProps, props, {\n    components: components,\n    mdxType: \"MDXLayout\"\n  }), mdx(\"p\", null, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Cause[E]\"), \" is a description of a full story of failure, which is included in an \", mdx(\"a\", {\n    parentName: \"p\",\n    \"href\": \"exit.md\"\n  }, \"Exit.Failure\"), \". Many times in ZIO something can fail for a value of type \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"E\"), \", but there are other ways things can fail too.\"), mdx(\"p\", null, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"IO[E, A]\"), \" is polymorphic in values of type \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"E\"), \" and we can work with any error type that we want, but there is a lot of information that is not inside an arbitrary \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"E\"), \" value. So as a result ZIO needs somewhere to store things like \", mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"unexpected exceptions or defects\"), \", \", mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"stack and execution traces\"), \", \", mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"cause of fiber interruptions\"), \", and so forth.\"), mdx(\"h2\", null, \"Cause Variations\"), mdx(\"p\", null, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Cause\"), \" has several variations which encode all the cases:\"), mdx(\"ol\", null, mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(\"p\", {\n    parentName: \"li\"\n  }, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Fail[+E](value: E)\"), \" contains the cause of expected failure of type \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"E\"), \".\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(\"p\", {\n    parentName: \"li\"\n  }, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Die(value: Throwable)\"), \" contains the cause of a defect or in other words, an unexpected failure of type \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Throwable\"), \". If we have a bug in our code and something throws an unexpected exception, that information would be described inside a Die.\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(\"p\", {\n    parentName: \"li\"\n  }, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Interrupt(fiberId)\"), \" contains information of the fiber id that causes fiber interruption.\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(\"p\", {\n    parentName: \"li\"\n  }, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Traced(cause, trace)\"), \" store stack traces and execution traces.\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(\"p\", {\n    parentName: \"li\"\n  }, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Meta(cause, data)\"))), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(\"p\", {\n    parentName: \"li\"\n  }, mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Both(left, right)\"), \" & \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Then(left, right)\"), \" store composition of two parallel and sequential causes. Sometimes fibers can fail for more than one reason. If we are doing two things at once and both of them fail then we actually have two errors. Examples:\"))), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"If we perform ZIO's analog of try-finally (e.g. ZIO#ensuring), and both of \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"try\"), \" and \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"finally\"), \" blocks fail, so their causes are encoded with \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"Then\"), \".\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"If we run two parallel fibers with \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"zipPar\"), \" and all of them fail, so their causes will be encoded with \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"Both\"), \".\")), mdx(\"p\", null, \"Let's try to create some of these causes:\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-scala\"\n  }, \"import zio._\\nimport zio.duration._\\nfor {\\n  failExit <- ZIO.fail(\\\"Oh! Error!\\\").run\\n  dieExit  <- ZIO.effectTotal(5 / 0).run\\n  thenExit <- ZIO.fail(\\\"first\\\").ensuring(ZIO.die(throw new Exception(\\\"second\\\"))).run\\n  bothExit <- ZIO.fail(\\\"first\\\").zipPar(ZIO.die(throw new Exception(\\\"second\\\"))).run\\n  fiber    <- ZIO.sleep(1.second).fork\\n  _        <- fiber.interrupt\\n  interruptionExit <- fiber.join.run\\n} yield ()\\n\")), mdx(\"h2\", null, \"Lossless Error Model\"), mdx(\"p\", null, \"ZIO is very aggressive about preserving the full information related to a failure. ZIO capture all type of errors into the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Cause\"), \" data type. So its error model is lossless. It doesn't throw information related to the failure result. So we can figure out exactly what happened during the operation of our effects.\"));\n}\n;\nMDXContent.isMDXComponent = true;"}},"pageContext":{"filePath":"/home/runner/work/gatsby-theme-zio/gatsby-theme-zio/example/node_modules/@atooni/zio-core/src/docs/datatypes/core/cause.md"}},"staticQueryHashes":[]}